import { Course } from './types';

export const COURSES: Course[] = [
  {
    id: '1',
    title: 'Dasar Digital Marketing untuk Pemula',
    description: 'Pelajari strategi pemasaran digital yang efektif untuk membangun brand dan meningkatkan penjualan.',
    price: 0,
    isFree: true,
    category: 'Digital Marketing',
    level: 'Pemula',
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=800',
    instructor: 'Andi Saputra',
    duration: '4 Jam',
  },
  {
    id: '2',
    title: 'Strategi Menjadi Influencer Sukses',
    description: 'Cara membangun personal branding dan engagement tinggi di media sosial.',
    price: 350000,
    isFree: false,
    category: 'Influencer',
    level: 'Menengah',
    thumbnail: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&q=80&w=800',
    instructor: 'Sari Wijaya',
    duration: '6 Jam',
  },
  {
    id: '3',
    title: 'Mastering Twitch & Youtube Streaming',
    description: 'Teknis setup, interaksi audiens, hingga monetisasi konten live streaming.',
    price: 499000,
    isFree: false,
    category: 'Streamer',
    level: 'Pemula',
    thumbnail: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&q=80&w=800',
    instructor: 'Reza Pratama',
    duration: '10 Jam',
  },
  {
    id: '4',
    title: 'Business Analyst Fundamental',
    description: 'Belajar menganalisis kebutuhan bisnis dan memberikan solusi berbasis data.',
    price: 750000,
    isFree: false,
    category: 'Business Analyst',
    level: 'Menengah',
    thumbnail: 'https://images.unsplash.com/photo-1454165833767-027ffea9e77b?auto=format&fit=crop&q=80&w=800',
    instructor: 'Budi Santoso',
    duration: '15 Jam',
  },
  {
    id: '5',
    title: 'Data Science dengan Python',
    description: 'Langkah awal menjadi Data Scientist dengan pengolahan data menggunakan Python.',
    price: 0,
    isFree: true,
    category: 'Data Scientist',
    level: 'Pemula',
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=800',
    instructor: 'Dewi Lestari',
    duration: '5 Jam',
  },
  {
    id: '6',
    title: 'Membangun Startup Dari Nol',
    description: 'Dari ide hingga MVP. Pelajari fundamental startup ekosistem di Indonesia.',
    price: 899000,
    isFree: false,
    category: 'Startup',
    level: 'Lanjutan',
    thumbnail: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&q=80&w=800',
    instructor: 'Kevin Sanjaya',
    duration: '20 Jam',
  },
  {
    id: '7',
    title: 'Seni Kerja Remote & Produktivitas',
    description: 'Tips mendapatkan pekerjaan remote global dan tetap produktif di rumah.',
    price: 0,
    isFree: true,
    category: 'Remote Work',
    level: 'Pemula',
    thumbnail: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?auto=format&fit=crop&q=80&w=800',
    instructor: 'Rina Kartika',
    duration: '3 Jam',
  },
];
